### ISSUE TITLE
License.md?

### ISSUE THREAD

**Issue by kamn** [primaryobjects/AI-Programmer#3]
I think this project is really interesting and wanted to modify somethings(like adding cudafy) but I was wondering if you had given any thought to adding a license to the project? Thanks!

**Comment by primaryobjects** [comment]
I haven't added a specific license, beyond a copyright to the project. Please feel free to experiment. Let me know if you're able to gain any performance improvements via cudafy. Thanks.

**Comment by createthis** [comment]
Just an FYI: I personally won't be touching or looking at the code without a license in place. I don't need a lawsuit if I learn something useful. Licenses protect developers and encourage collaboration by setting the terms of contributions. I view projects without a license as honeypots for legal issues. Consider Zenimax vs Oculus recently, for example.

Cool project though. I enjoyed the articles.

**Comment by UndiFineD** [comment]
+1

**Comment by jay-bricksoft** [comment]
+1
