### ISSUE TITLE
Scoring Enhancement?

### ISSUE THREAD

**Issue by euphoricz** [primaryobjects/AI-Programmer#8]
I just want to start off by saying this is fascinating, great work.

I have been developing software for almost 20 years but have only just started to scratch the surface on AI.

There is a ton of useful information in this project that has been very helpful to me, so thank you.

I did notice a couple of things regarding the scoring system and elitism.

I think scoring is by far one of the best methods to increase performance, especially if performance itself is also what is being scored.
In other words, if two genomes have a score of 700 but achieved that fitness in different ways, then a secondary score for performance or time to execute could drastically enhance scoring and reduce the time it takes to test, allowing for more generations to be created and tested.
This additional performance scoring could also be used to dynamically determine max number of applicable loops, instead of hard coding a max.

Regarding elitism, by definition it is supposed to ensure the best genes are retrained in case mutation has a negative impact, in essence it provides stability.  Looking at the code however it seems the last two genomes of the current generation are being added to the next generation.  I could be missing something and probably am, but shouldn't this be picking the two best scoring genomes of the current generation to be copied into the next generation?

Thanks again for the great code and articles!
Nick Hanshaw

**Comment by primaryobjects** [comment]
Thank you for checking out there project. Regarding your question, the genomes are [sorted](https://github.com/primaryobjects/AI-Programmer/blob/master/AIProgrammer.GA/GA.cs#L211). Thank you.

**Comment by euphoricz** [comment]
Ah, I see you have also accounted for number of operations in scoring, awesome.

Sorry for the noob questions, thanks for the clarification.
